name: SlateDocs Builder
description: A Github Action that allows you to build slate documentation.
author: JoshAS <josh@asteriskstudios.co.uk>

inputs:
  docsPath:
    description: "Path to the folder containing your .md files, from the root of the repo. Defaults to the root folder"
    required: false
    default: "/"

runs:
  using: "composite"
  steps:
    - run: docker build --tag slatebuilder /github/workspace/
      shell: sh
    - run: docker run --rm --env SLATE_DOCS_PATH=${{inputs.docsPath}} -v $(pwd)${{inputs.docsPath}}:/usr/src/docs -v $(pwd)/build:/usr/src/build slatebuilder env
      shell: sh

branding: 
  icon: align-center
  color: orange