name: SlateDocs Builder
description: A Github Action that allows you to build slate documentation.
author: JoshAS <josh@asteriskstudios.co.uk>
runs:
  using: "docker"
  image: "Dockerfile"

branding: 
  icon: align-center
  color: orange